# Generated by Django 5.0.2 on 2024-05-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(max_length=200)),
                ('BlogorName', models.CharField(max_length=100)),
                ('Blog_TEXT', models.TextField()),
                ('BlogorPhoto', models.ImageField(upload_to='images/')),
                ('PUB_DATE_TIME', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummitTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summit_Title', models.CharField(max_length=200)),
                ('Summitor_Name', models.CharField(max_length=100)),
                ('Summitor_Bio', models.TextField()),
                ('Summit_Text', models.URLField()),
                ('Summitor_Photo', models.ImageField(upload_to='images/')),
                ('PUB_DATE_TIME', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
